### ISSUE TITLE
Restructure repo

### ISSUE THREAD

**Issue by markus-kre** [joeyklee/itp-resource-collector#3]
@joeyklee I noticed that our resource collector has a bunch of different components/prototypes already (authentication, extension prototype, access tokens,...). So I thought it would make sense to structure the repo a bit more. I think we should have a folder for each prototype we develop (like the chrome-extension folder) and keep the main readme + folder clean and more high level. By high level I mean sth like the user flow sketch I just added. I think it will help us to keep an overview of what we are doing, but the have a deeper dive in each prototype folder. Lets talk about this later :)

**Comment by joeyklee** [comment]
@mmmmmmmmmmmmmmmm 👍 
+ Sure - we can separate into something `itp-resource-collector/chrome-extension`, `itp-resource-collector/server`, etc... 

+ re `chrome-extension`: we def. should make a general web browser extension, but I know we're both on the same page here ;) 

+ Nice user flow sketch! There might be a step or two (e.g. a visual UI wrapper around github issues tagged resources) we can add, but generally, yes, this feels right to me. Thanks!
